package javaapplication2;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ravig
 */
public class Assignment1 extends javax.swing.JFrame {

    /**
     * Creates new form Assignment1
     */
    public Assignment1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/logo.png"))); // NOI18N

        jSeparator1.setPreferredSize(new java.awt.Dimension(1500, 10));

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Selection By - RaviKant");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Explore");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/search.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel8.setText("What's your favourite Product ?");

        jLabel9.setText("Lorem ipsum dolor sit amet, cur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euismod eu quam. Etiam eget egestas metus. In a gravida ex. Maecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel5.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euisMaecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel6.setText(" minute & important details of the product they are currently using and its importance");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/search.jpg"))); // NOI18N
        jLabel4.setText("jLabel3");

        jLabel10.setText("Lorem ipsum dolor sit amet, cur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euismod eu quam. Etiam eget egestas metus. In a gravida ex. Maecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel7.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euisMaecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel11.setText(" minute & important details of the product they are currently using and its importance");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/search.jpg"))); // NOI18N
        jLabel12.setText("jLabel3");

        jLabel13.setText("Lorem ipsum dolor sit amet, cur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euismod eu quam. Etiam eget egestas metus. In a gravida ex. Maecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel14.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euisMaecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel15.setText(" minute & important details of the product they are currently using and its importance");

        jLabel16.setText(" minute & important details of the product they are currently using and its importance");

        jLabel17.setText("Lorem ipsum dolor sit amet, cur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euismod eu quam. Etiam eget egestas metus. In a gravida ex. Maecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel18.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euisMaecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/search.jpg"))); // NOI18N
        jLabel19.setText("jLabel3");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/search.jpg"))); // NOI18N
        jLabel20.setText("jLabel3");

        jLabel21.setText("Lorem ipsum dolor sit amet, cur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euismod eu quam. Etiam eget egestas metus. In a gravida ex. Maecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel22.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euisMaecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel23.setText(" minute & important details of the product they are currently using and its importance");

        jSeparator2.setPreferredSize(new java.awt.Dimension(1500, 10));

        jLabel25.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel25.setText("Facts About Basket-Ball");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/basket ball.jpg"))); // NOI18N

        jLabel27.setText("Lorem ipsum dolor sit amet, cur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euismod eu quam. Etiam eget egestas metus. In a gravida ex. Maecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel28.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euisMaecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel29.setText(" minute & important details of the product they are currently using and its importance");

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Explore");

        jSeparator3.setPreferredSize(new java.awt.Dimension(1500, 10));

        jLabel46.setBackground(new java.awt.Color(0, 0, 153));
        jLabel46.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 102, 255));
        jLabel46.setText("Selection By - RaviKant");
        jLabel46.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/basket ball.jpg"))); // NOI18N

        jLabel48.setText("Lorem ipsum dolor sit amet, cur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euismod eu quam. Etiam eget egestas metus. In a gravida ex. Maecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel49.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euisMaecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel50.setText(" minute & important details of the product they are currently using and its importance");

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/basket ball.jpg"))); // NOI18N

        jLabel52.setText("Lorem ipsum dolor sit amet, cur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euismod eu quam. Etiam eget egestas metus. In a gravida ex. Maecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel53.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euisMaecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel54.setText(" minute & important details of the product they are currently using and its importance");

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/basket ball.jpg"))); // NOI18N

        jLabel56.setText("Lorem ipsum dolor sit amet, cur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euismod eu quam. Etiam eget egestas metus. In a gravida ex. Maecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel57.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euisMaecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel58.setText(" minute & important details of the product they are currently using and its importance");

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/basket ball.jpg"))); // NOI18N

        jLabel60.setText("Lorem ipsum dolor sit amet, cur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euismod eu quam. Etiam eget egestas metus. In a gravida ex. Maecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel61.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer augue mi, efficitur sed tempor id, ultrices aliquet magna. Maecenas elementum lorem nec ultricies suscipit. Integer at consectetur quam. Ut bibendum leo a odio vehicula rutrum. Ut vehicula risus ante, a hendrerit dolor ultrices eu. Donec aliquam et enim sed molestie. Morbi tincidunt, velit eu tempor efficitur, neque ipsum malesuada neque, et iaculis quam diam ac tellus. Curabitur scelerisque vel est dictum dictum. Nulla sem mauris, sollicitudin eu gravida vel, euisMaecenas dignissim a turpis a aliquam. Pellentesque id ex non nisl ullamcorper dictum nec sed lacus. Pellentesque imperdiet pulvinar commodo.");

        jLabel62.setText(" minute & important details of the product they are currently using and its importance");

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Next");

        jButton6.setBackground(new java.awt.Color(0, 0, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Prev ");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setText("2/10");
        jTextField1.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel26)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addGap(17, 17, 17))
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addGap(17, 17, 17))
                            .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addGap(17, 17, 17))
                            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel57, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addGap(17, 17, 17))
                            .addComponent(jLabel62, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel60, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(256, 256, 256))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(638, 638, 638)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(42, 42, 42))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(578, 578, 578))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(260, 260, 260)))
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(447, 447, 447))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16))))))))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jLabel46))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel48)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel49)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel50))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel52)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel53)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel54))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel56)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel57)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel58)))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel62)
                                .addGap(6, 6, 6)))))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignment1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
